"""initial_phase11_persistence

Revision ID: 21a1286fa764
Revises: 
Create Date: 2026-09-21 13:10:16.058609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a1286fa764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_tags_name'), 'security_tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('forensic_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_cases_assigned_to'), 'forensic_cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_forensic_cases_status'), 'forensic_cases', ['status'], unique=False)
    op.create_index(op.f('ix_forensic_cases_title'), 'forensic_cases', ['title'], unique=False)
    op.create_table('mailboxes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('mailbox_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email_address', name='uq_mailbox_user_address')
    )
    op.create_index(op.f('ix_mailboxes_email_address'), 'mailboxes', ['email_address'], unique=False)
    op.create_index(op.f('ix_mailboxes_user_id'), 'mailboxes', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('mailbox_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('reply_to', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('body_text_preview', sa.Text(), nullable=True),
    sa.Column('attachment_metadata', sa.JSON(), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=False),
    sa.Column('received_hops', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_mailbox_id'), 'emails', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_emails_message_id'), 'emails', ['message_id'], unique=True)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_sender_address'), 'emails', ['sender_address'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('threat_confidence', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('canonical_features', sa.JSON(), nullable=True),
    sa.Column('analyzer_results', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_classification'), 'analysis_runs', ['classification'], unique=False)
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_email_id'), 'analysis_runs', ['email_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_risk_level'), 'analysis_runs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('case_emails',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'email_id')
    )
    op.create_table('analysis_run_tags',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['security_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'tag_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('extracted_facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_analysis_id'), 'evidence', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_email_id'), 'evidence', ['email_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_sha256_hash'), 'evidence', ['sha256_hash'], unique=False)
    op.create_table('ml_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=False),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_results_analysis_id'), 'ml_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ml_results_email_id'), 'ml_results', ['email_id'], unique=False)
    op.create_index(op.f('ix_ml_results_model_name'), 'ml_results', ['model_name'], unique=False)
    op.create_index(op.f('ix_ml_results_prediction'), 'ml_results', ['prediction'], unique=False)
    op.create_index(op.f('ix_ml_results_status'), 'ml_results', ['status'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('spam_category', sa.String(length=50), nullable=True),
    sa.Column('gateway_category', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_action'), 'policy_decisions', ['action'], unique=False)
    op.create_index(op.f('ix_policy_decisions_analysis_id'), 'policy_decisions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_classification'), 'policy_decisions', ['classification'], unique=False)
    op.create_index(op.f('ix_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_email_id'), 'policy_decisions', ['email_id'], unique=False)
    op.create_table('security_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_analysis_id'), 'security_findings', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_security_findings_code'), 'security_findings', ['code'], unique=False)
    op.create_index(op.f('ix_security_findings_email_id'), 'security_findings', ['email_id'], unique=False)
    op.create_index(op.f('ix_security_findings_severity'), 'security_findings', ['severity'], unique=False)
    op.create_table('case_evidence',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['forensic_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'evidence_id')
    )
    op.create_table('delivery_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=False),
    sa.Column('policy_decision_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_action'), 'delivery_events', ['action'], unique=False)
    op.create_index(op.f('ix_delivery_events_created_at'), 'delivery_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_delivery_events_email_id'), 'delivery_events', ['email_id'], unique=False)
    op.create_index(op.f('ix_delivery_events_policy_decision_id'), 'delivery_events', ['policy_decision_id'], unique=False)
    op.create_index(op.f('ix_delivery_events_status'), 'delivery_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_events_status'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_policy_decision_id'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_email_id'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_created_at'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_action'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_table('case_evidence')
    op.drop_index(op.f('ix_security_findings_severity'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_email_id'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_code'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_analysis_id'), table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_policy_decisions_email_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_created_at'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_classification'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_analysis_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_action'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_ml_results_status'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_prediction'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_model_name'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_email_id'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_analysis_id'), table_name='ml_results')
    op.drop_table('ml_results')
    op.drop_index(op.f('ix_evidence_sha256_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_email_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_analysis_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('analysis_run_tags')
    op.drop_table('case_emails')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_risk_level'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_email_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_classification'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender_address'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_mailbox_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_mailboxes_user_id'), table_name='mailboxes')
    op.drop_index(op.f('ix_mailboxes_email_address'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_forensic_cases_title'), table_name='forensic_cases')
    op.drop_index(op.f('ix_forensic_cases_status'), table_name='forensic_cases')
    op.drop_index(op.f('ix_forensic_cases_assigned_to'), table_name='forensic_cases')
    op.drop_table('forensic_cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_tags_name'), table_name='security_tags')
    op.drop_table('security_tags')
    # ### end Alembic commands ###
